# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 03:27
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u6b63\u6587'),
        ),
    ]
